image: 
  file: Dockerfile

tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    init: |
      bash -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/main/install.sh | bash -s -"

  # --------------------------------------
  #  SETUP CQLSH and Create DB Workshop

  # --------------------------------------
  - name: working-terminal
    init: |
      echo "Welcome to the FusionAuth GitPod instance"
