tasks:
  

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    init: |
      sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/main/install.sh | sh"

  # --------------------------------------
  #  SETUP CQLSH and Create DB Workshop
  # --------------------------------------
  - name: working-terminal
    command: |
      echo "Welcome to the FusionAuth GitPod instance"
