image: gitpod/workspace-postgres

tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    init: |
      apt-get install gh
      fusionauth/bin/startup.sh

  # --------------------------------------
  - name: working-terminal
    init: |
      echo "Welcome to the FusionAuth GitPod instance"

ports:
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore 
    visibility: public
  - port: 9011
    onOpen: ignore
    visibility: public
