image: 
  file: Dockerfile

tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    env: 
      DATABASE_URL: "jdbc:postgresql://localhost:5432/fusionauth"
      DATABASE_ROOT_USERNAME: "postgres"
      DATABASE_ROOT_PASSWORD: "password"
      FUSIONAUTH_APP_KICKSTART_FILE: "/workspace/fusionauth-quickstart-javascript-react-web/kickstart/kickstart.json"
    command: |
      /workspace/fusionauth-quickstart-javascript-react-web/install.sh
      fusionauth/bin/startup.sh
      gp open README.md

  # --------------------------------------
  - name: working-terminal
    openMode: split-right

ports:
  - port: 3000
    onOpen: ignore 
    visibility: public
  - port: 9011
    onOpen: open-preview
    visibility: public
  - port: 9012
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
