image: 
  file: Dockerfile


tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    init: |
      fusionauth/bin/startup.sh

  # --------------------------------------
  - name: working-terminal
    init: |
      echo "Welcome to the FusionAuth GitPod instance"

ports:
  - port: 8888
    onOpen: open-preview
    visibility: public
  - port: 3000
    onOpen: ignore 
    visibility: public
  - port: 9011
    onOpen: ignore
    visibility: public
