image: 
  file: Dockerfile

tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth
    env: 
      DATABASE_URL: "jdbc:postgresql://localhost:5432/fusionauth"
      DATABASE_ROOT_USERNAME: "gitpod"
      DATABASE_ROOT_PASSWORD: "password"
      FUSIONAUTH_APP_KICKSTART_FILE: "/workspace/fusionauth-quickstart-javascript-react-web/kickstart/kickstart.json"
      INSTALL_SEARCH: 1
    init: |
      bash /workspace/fusionauth-quickstart-javascript-react-web/install.sh   
      bash /workspace/fusionauth-quickstart-javascript-react-web/ports.sh
      

ports:
  - port: 9011
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 9012
    onOpen: ignore
    visibility: public
  - port: 9020
    onOpen: ignore
    visibility: public
  - port: 9021
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
    
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
