image: gitpod/workspace-postgres

tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    env: 
      DATABASE_URL: "jdbc:postgresql://localhost:5432/fusionauth"
    init: |
      apt-get install gh
      psql -c "CREATE USER postgres WITH SUPERUSER PASSWORD 'password';"
      bash -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/main/install.sh | bash -s -"
      fusionauth/bin/startup.sh

  # --------------------------------------
  - name: working-terminal
    init: |
      echo "Welcome to the FusionAuth GitPod instance"

ports:
  - port: 3000
    onOpen: ignore 
    visibility: public
  - port: 9011
    onOpen: open-preview
    visibility: public
  - port: 9012
    onOpen: ignore
    visibility: public
