image: gitpod/workspace-postgres

tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: fusionauth-server
    env: 
      DATABASE_URL: "jdbc:postgresql://localhost:5432/fusionauth"
      DATABASE_ROOT_USERNAME: "postgres"
      DATABASE_ROOT_PASSWORD: "password"
      FUSIONAUTH_APP_KICKSTART_FILE: "/workspace/fusionauth-quickstart-javascript-react-web/kickstart/kickstart.json"
    init: |
      psql -c "CREATE USER postgres WITH SUPERUSER PASSWORD 'password';"
      bash -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/main/install.sh | bash -s -"
    command: |
      fusionauth/bin/startup.sh
      gp open README.md

  # --------------------------------------
  - name: working-terminal

ports:
  - port: 3000
    onOpen: ignore 
    visibility: public
  - port: 9011
    onOpen: open-preview
    visibility: public
  - port: 9012
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
